name: datastore_client
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build_context: 2.0.4
  dartz: 0.9.2
  equatable: ^1.2.5
  flushbar: 1.10.4
  flutter_bloc: 6.0.6
  flutter_hooks: 0.14.1
  font_awesome_flutter: 8.10.0
  freezed_annotation: 0.12.0
  google_fonts: 1.1.1
  hive: 1.4.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  build_runner: 1.10.4
  freezed: 0.12.2
  json_serializable: ^3.5.0
  lint: ^1.3.0
  mockito: ^4.1.3

flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
